/*
Joseph Wong
April 13, 2022
Pipeline for sample_code1: This pipeline builds, checks code quality, checks code quantity, conditionally runs a script, and zips files into a build artifact for a python application
*/

pipeline {
    agent any

    parameters {
        string(name: 'TARGET', defaultValue: '', description: 'Run Target Scripts')
    }

    stages {
        stage("Build") {
            steps {
                sh 'echo "Running The Requirements..."'
                sh 'pip install -r requirements.txt'
                sh 'echo "Requirements Complete"'
            }
        }
        stage("Code Quality") {
            steps {
                sh 'pylint-fail-under --fail_under 7.0 *.py'
            }
        }
        stage("Code Quantity") {
            steps {
                sh 'wc -l *.py'
            }
        }
        stage("Run Scripts") {
            when {
                expression { params.TARGET == "run" }
            }
            steps {
                sh 'python3 main.py phone text output'
                sh 'python3 main.py tablet csv output'
                sh 'python3 main.py laptop json output'
            }
        }
        stage("Zip") {
            steps {
                sh 'zip sample1.zip *.py'
                archiveArtifacts artifacts: 'sample1.zip', fingerprint: true, onlyIfSuccessful: true
                sh 'echo "Student Number: A01188820"'
                sh 'echo "Group Number: 44"'
            }
        }
    }
}
