/*
Joseph Wong
April 13, 2022
Description
*/
/*


5. Stage called Zip that creates a zipfile containing all the .py files in the project (3 files - main.py, data.py, report.py). The Python filenames should not be hard-coded. The zipfile should be made into a build artifact (i.e., it is available for download on the main Jenkins job page).
In one of the above stages, output your Student Number and Group Number so that it shows up in the Console Output. You will need this for the screenshot required in the next question.

Hints:

You can use the echo keyword to print text to the console.
For the Code Quantity Stage, you can use the "wc -l" command to get the number of lines in a file. You may want to Google this command or use the Linux man pages.
*/

pipeline {
    agent any

    parameters {
        string(name: 'TARGET', defaultValue: '', description: 'Run Target Scripts')
    }

    stages {
        stage("Build") {
            steps {
                sh 'echo "Running The Requirements..."'
                sh 'pip install -r requirements.txt'
                sh 'echo "Requirements Complete"'
            }
        }
        stage("Code Quality") {
            steps {
                sh 'pylint-fail-under --fail_under 7.0 *.py'
            }
        }
        stage("Code Quantity") {
            steps {
                sh 'wc -l *.py'
            }
        }
        stage("Run Scripts") {
            when {
                expression { params.TARGET == "run" }
            }
            steps {
                sh 'python3 main.py phone text output'
                sh 'python3 main.py tablet csv output'
                sh 'python3 main.py laptop json output'
            }
        }
    }
}
